src/main/kotlin/gg/essential/elementa/utils/options.kt

Previously, these would always just be false (as they weren't set anywhere). Not totally sure what the point of having these fields configured like this is, but at least they work now.

Options: Initialize elementa{Dev,Debug} from VM options

---

src/main/kotlin/gg/essential/elementa/components/TreeListComponent.kt

Now, when a user holds shift and clicks a TreeList's Node's
ArrowComponent, that node will recursively close (if it is open) or
open (if it is closed) all child nodes under itself.

TreeListComponent: Recursively open/close components when holding shift

---

src/main/kotlin/gg/essential/elementa/constraints/resolution/ConstraintResolutionGui.kt

This is the way the Inspector does it, and I think it's much better.
The hex code was to uniquely identifier the component in the list view,
but if the user is having trouble determining the components from the
list view, they should either look at the tree view or use delegation
to set the component names.

ConstraintResolutionGui: Display the component class and name

---

src/main/kotlin/gg/essential/elementa/markdown/drawables/ParagraphDrawable.kt

This is very much possible if the component's width is tiny (i.e. 0), so the error message should be more helpful.

MarkdownComponent: Improve ParagraphDrawable error message

---

src/main/kotlin/gg/essential/elementa/markdown/MarkdownComponent.kt
src/main/kotlin/gg/essential/elementa/markdown/drawables/ParagraphDrawable.kt

- Fix inline images _always_ crashing
- Fix `SoftBreakDrawable` after a code-styled text causing a weird empty code-styled drawable to appear
- Fix `HardBreakDrawable` causing a crash when present in a `ParagraphDrawable`

MarkdownComponent: Fix a couple bugs

---

src/main/kotlin/gg/essential/elementa/dsl/animations.kt

To allow for better chaining, as normally it will cast itself to a UIComponent, which is problematic when assigning to any other type of component.

Use extended generics rather than UIComponent

---

src/main/kotlin/gg/essential/elementa/markdown/MarkdownComponent.kt

An optional argument was added to the constructor in 9ea0135, which removes the
old synthetic Kotlin defaults constructor. To preserve binary compatibility, we
need to keep the original constructor overload with the exact same optional
arguments as it always used to have.

MarkdownComponent: Fix ABI backwards compatibility

---

src/main/kotlin/gg/essential/elementa/markdown/MarkdownComponent.kt

> Cause that's the place where layout is supposed to take place. One reason for
why this is the better place is that `draw` isn't called until the component is
drawn, and elementa doesn't draw components if they're not visible, therefore
markdown components where pretty much unusable with scrollbars cause their size
would be all wrong.
Sort of by necessity, this also fixes a bunch more things in MarkdownComponent:
>  MarkdownComponent: Stop abusing afterInitialization method
>
> There's no need for MarkdownComponent to override it, and then having to
manually call it because it can't call super.draw because that's too later for
when it wishes to draw.
>
> Also happens to fix effect initialization (which happened in the original
afterInitialization), the effect before draw callback (which …

MarkdownComponent: Layout in animationFrame instead of draw

---

src/main/kotlin/gg/essential/elementa/constraints/CramSiblingConstraint.kt

Due to the precision and accuracy limitations of floating-point numbers, situations can arise where two numbers should be exactly the same but in practice have a small difference in their value. In order to correct for this, a very small offset is introduced to ensure the `CramSiblingConstraint` constraint behaves as expended.

CramSiblingConstraint: Resolve incorrect behavior stemming from floating point limitations

---

README.md
build.gradle.kts
settings.gradle.kts
src/main/kotlin/gg/essential/elementa/markdown/MarkdownRenderer.kt
src/main/kotlin/gg/essential/elementa/svg/SVGParser.kt
src/main/kotlin/gg/essential/elementa/svg/data/SVGCircle.kt
src/main/kotlin/gg/essential/elementa/svg/data/SVGLine.kt
src/main/kotlin/gg/essential/elementa/svg/data/SVGPolyline.kt
src/main/kotlin/gg/essential/elementa/svg/data/SVGRect.kt

By relocating and bundling them ourselves. This way no consumer has to care
about our internal dependencies (and can't accidentally forget about them) and
Fabric users do not need to JiJ additional non-mod libraries to use
Elementa (only Elementa and UniversalCraft).

Build: Keep our internal dependencies entirely internal

---

src/main/kotlin/gg/essential/elementa/components/UIImage.kt
src/main/kotlin/gg/essential/elementa/components/image/BlurHashImage.kt
src/main/kotlin/gg/essential/elementa/components/image/MSDFComponent.kt

These don't actually do anything useful because ReleasedDynamicTexture already
takes care of cleaning up after itself.
Quite the opposite actually, they double-free and they call OpenGL methods from
an arbitrary thread (which most likely won't have the appropriate GL context
bound) crashing the JVM in the worst case.

Misc: Remove broken finalizers

---

build.gradle.kts

(requires essential-gradle-toolkit 0.1.5 to actually fix the issue; merge #58 first)
Because it tries to read a file from the same package but the string containing
that path did not get remapped.
Bumps essential-gradle-toolkit because previous versions did not remap
directory-like strings (those with an initial `/`).

Build: Fix Html5Entities throwing due to relocation

---

api/Elementa.api
src/main/kotlin/gg/essential/elementa/UIComponent.kt
src/main/kotlin/gg/essential/elementa/components/UIPoint.kt
src/main/kotlin/gg/essential/elementa/components/Window.kt
src/main/kotlin/gg/essential/elementa/components/inspector/ArrowComponent.kt

Because it's easy to forget to call that, especially because no one really tells
you that you have to do it. That part is fixed now.

UIComponent: Warn when beforeDraw wasn't called

---

api/Elementa.api
src/main/java/com/example/examplemod/ComponentsGui.kt
src/main/java/com/example/examplemod/ExampleGui.kt
src/main/java/com/example/examplemod/ExampleServerList.kt
src/main/java/com/example/examplemod/ExamplesGui.kt
src/main/java/com/example/examplemod/JavaTestGui.java
src/main/java/com/example/examplemod/KtTestGui.kt
src/main/kotlin/gg/essential/elementa/ElementaVersion.kt
src/main/kotlin/gg/essential/elementa/UIComponent.kt
src/main/kotlin/gg/essential/elementa/WindowScreen.kt
src/main/kotlin/gg/essential/elementa/components/Window.kt
src/main/kotlin/gg/essential/elementa/constraints/resolution/ConstraintResolutionGui.kt

This PR exists to improve Elementa mouse input by introducing Elementa Version v2.
1. In Minecraft versions <=1.12.2, the game calculates the position of the mouse input in an integer context
relative to scaled pixels. However, Elementa uses real pixels to determine the position of components leading
to situations where certain components or parts of components are not clickable due the game truncating the decimal.
This Elementa version improves this behavior by restoring the decimal component of mouse clicks to the mouse positions
on affected versions.
2. Minecraft mouse click input is positioned in the top left corner of a pixel. As a result, the left and top pixel of
a component do not register clicks and components with a width or height of 1 are also not clickable. This Elementa …

Improve mouse input

---

api/Elementa.api
src/main/kotlin/gg/essential/elementa/components/GradientComponent.kt
src/main/kotlin/gg/essential/elementa/components/UIText.kt
src/main/kotlin/gg/essential/elementa/components/UIWrappedText.kt
src/main/kotlin/gg/essential/elementa/components/input/UIPasswordInput.kt
src/main/kotlin/gg/essential/elementa/constraints/ColorConstraints.kt
src/main/kotlin/gg/essential/elementa/constraints/PixelConstraint.kt
src/main/kotlin/gg/essential/elementa/constraints/RelativeConstraint.kt
src/main/kotlin/gg/essential/elementa/constraints/ScaleConstraint.kt
src/main/kotlin/gg/essential/elementa/effects/OutlineEffect.kt
src/main/kotlin/gg/essential/elementa/effects/RecursiveFadeEffect.kt

Previously, state fields were mutable and reassigned when rebound which caused potentially undesired behavior. These commits change those fields from being mutable to immutable mapped states which are rebound to the new state value.
Fixes [EM-420](https://linear.app/sparkuniverse/issue/EM-420)

Fix State Usages

---

build.gradle.kts
versions/build.gradle.kts

Internal dependencies used to be added directly to the project's classpath and
its jar but that means that dependent projects did not inherit it. As such it
wasn't possible to run e.g. 1.12.2 in dev because the relocated internal
dependencies were not on its classpath.
This commit changes that such that the internal dependencies jar is now a
regular dependency of the common project and as a result it's inherited by the
platform projects.
That would however result in the internal dependencies being bundled twice (once
in the common jar, and then a second time in the platform jar), so we skip the
first one by no longer using the `makeConfigurationForInternalDependencies`
method.
We also change the Kotlin dependencies in the common project to be
`compileOnly`, so they are not inherited by …

Build: Fix internal dependencies not being available in dev

---

src/main/kotlin/gg/essential/elementa/components/UIImage.kt

Previously, UIImage would set its `texture` field as soon as it's available from the future callback. However, the texture was not uploaded until the next frame via `Window.enqueueRenderOperation`. As a result, calls to `supply` could apply the texture before the texture was uploaded. This has been fixed by not setting the field until the texture is uploaded.

UIImage: Address race condition in texture loading.

---

src/main/kotlin/gg/essential/elementa/components/ScrollComponent.kt

When the size of the ScrollComponent changes, we need to update the scrollbar
size accordingly.

ScrollComponent: Fix incorrect scrollbar when component is resized

---

api/Elementa.api
src/main/kotlin/gg/essential/elementa/markdown/MarkdownComponent.kt

Simple PR to make the `MarkdownConfig` inside a `MarkdownComponent` mutable via the `updateConfig` method. The component is parsed again and the layout is reconfigured whenever the config changes.

MarkdownComponent: Make config mutable

---

src/main/kotlin/gg/essential/elementa/components/ScrollComponent.kt

This PR fixes the scrollbar position when `verticalScrollOpposite` or `horizontalScrollOpposite` are set to true.

ScrollComponent: Fix scrollbar position when scroll direction is inverted

---

src/main/kotlin/gg/essential/elementa/VanillaFontRenderer.kt

If shadowColor was supplied, the text was rendered with a shadow regardless of what the value of shadow was. This has been fixed.
Fixes EM-796

VanillaFontRenderer: Obey passed value of shadow when rendering text.

---

api/Elementa.api
src/main/kotlin/gg/essential/elementa/markdown/MarkdownComponent.kt
src/main/kotlin/gg/essential/elementa/markdown/drawables/BlockquoteDrawable.kt
src/main/kotlin/gg/essential/elementa/markdown/drawables/HeaderDrawable.kt
src/main/kotlin/gg/essential/elementa/markdown/drawables/ListDrawable.kt
src/main/kotlin/gg/essential/elementa/markdown/drawables/ParagraphDrawable.kt
src/main/kotlin/gg/essential/elementa/markdown/drawables/TextDrawable.kt

This PR aims to improve line wrapping in Markdown components such that the line width accurately represents the actual width of a line.
This should be useful in cases where a component's width is adjusted relative to a Markdown component's line width(s) without resulting in arbitrary trailing whitespace.

EM-708 - Adjust Markdown wrapping to avoid extra whitespace

---

src/main/kotlin/gg/essential/elementa/components/UIWrappedText.kt

Previously, UIWrappedText's height would exceed the area it is rendered in when lineSpacing is greater than the size of each line

UIWrappedText: Constrain component height to render area

---

src/main/kotlin/gg/essential/elementa/utils/text.kt

If the `suffixWidth` is greater than `maxLineWidth * textScale` then the while loop will iterate until length = -1 and `contents.substring(0, length)` throws

Text: Ensure length is > 0

---

src/main/kotlin/gg/essential/elementa/components/UIImage.kt

Resolve #40 which talks of how UIImage's dont print exceptions because they have no exception handler nor utilise `CompleteableFuture#whenComplete`.
This PR resolves this by printing the exception IF the future throws an exception and returns the value as `null`,

UIImage: Print stacktrace for erroneous images

---

src/main/kotlin/gg/essential/elementa/constraints/ColorConstraints.kt

Previously RainbowColorConstraint would only set its initial color since `recalculate` was never being toggled back to true, rather than updating every frame.

RainbowColorConstraint: Fix color not changing automatically every frame

---

src/main/kotlin/gg/essential/elementa/components/Window.kt

This mainly occurs on LWJGL 2 versions of the game on macOS when pressing characters like F(n), Home, End, Delete, etc., but we should still exclude these characters nevertheless.

Window: Ignore character in `keyType` if it's in a private use area

---

src/main/kotlin/gg/essential/elementa/effects/RecursiveFadeEffect.kt

We must forward the constraint's animation frame to the original. We want colors to be recalculated when needed and this prevents that during the `RecursiveFadeEffect`'s lifecycle.
The `originalAlpha` member was also removed. It didn't appear like there was any reason for caching the alpha, and a use-case where someone might depend on that is quite a niche one (neither I nor Johni could think of one), and its removal is required for this change to be effective.

OverridableAlphaColorConstraint: Recalculate original constraint's color

---

src/main/kotlin/gg/essential/elementa/components/Window.kt

If the window is sufficiently complex, it's possible for the average `animationFrame` to take so long we'll start falling behind with no way to ever catch up. And the amount of frames we're behind will quickly grow to the point where we'll be spending five seconds in `animationFrame` before we can get a real frame on the screen.
Or even worse with the old while-loop, we'll be stuck indefinitely because the five seconds check only happens outside the loop and we never get to exit the loop if we never catch up, effectively locking up the game.
To prevent that, we limit the `animationFrame` calls we make per real frame such that we'll still be able to render approximately 30 real frames per second at the cost of animations slowing down.

Window: Fix live-lock when `animationFrame` is slow

---

src/main/kotlin/gg/essential/elementa/markdown/drawables/TextDrawable.kt

After styleChars is subtracted from splitPoint, the splitPoint value refers to indices in the plainText, not the formattedText.
Fixes EM-1599
Before: 
After:

TextDrawable: Fix incorrect splitting of formatted drawables

---

src/main/kotlin/gg/essential/elementa/components/ScrollComponent.kt

When a child is removed from the scroller via `removeChild`, we used to check if no children were left and if that was the case, we'd assume that the last child was just removed and therefore we need to add the `emptyText` back. This assumption however is incorrect when one considers `filterChildren` which too might add the `emptyText` if it filters out everything. In that case the empty text is already in the `actualHolder` and this code just adds a second one.
And even the next `addChild` will only remove one of the two, leaving you with mixed content which will likely blow up your comparator if you then try to `sortChildren`.
This commit fixes the issue by checking whether `actualHolder.children` is actually empty before adding the `emptyText`.
Fixes EM-1455

ScrollComponent: Fix duplicate emptyText

---

api/Elementa.api
src/main/kotlin/gg/essential/elementa/markdown/MarkdownComponent.kt
src/main/kotlin/gg/essential/elementa/markdown/drawables/Drawable.kt
src/main/kotlin/gg/essential/elementa/markdown/drawables/ImageDrawable.kt
src/main/kotlin/gg/essential/elementa/markdown/drawables/ParagraphDrawable.kt
src/main/kotlin/gg/essential/elementa/markdown/drawables/TextDrawable.kt

- Run necessary things related to location before drawing anything, fixes images lagging behind when mouse is hovering it and flickering when image just loaded
- Create `beforeDraw` function in `Drawable` since `TextDrawable` already had something like it and keeping it separate everywhere could result in a mess

Markdown: fix images flickering when loading and lagging behind when scrolling

---

api/Elementa.api
gradle/wrapper/gradle-wrapper.properties
gradlew
settings.gradle.kts
versions/build.gradle.kts

The changes to the API dump are presumably due to a bug fix in the Kotlin binary compatibility validator.

Build: Update to Gradle 8.2, Loom 1.2

---

api/Elementa.api
src/main/kotlin/gg/essential/elementa/ElementaVersion.kt
src/main/kotlin/gg/essential/elementa/UIComponent.kt

Prior to this, if you had two effects (e.g. ScissorEffect) of the same type on the same component, they would clash due to `afterDraw` being called in the same order as `beforeDraw`. Calling `afterDraw` on these effects in reverse solves the problem.
This also introduces a new Elementa version, V3 - which deprecates V2.

UIComponent: Call `afterDraw` on effects in reverse-order

---

.github/workflows/main.yml
README.md
settings.gradle.kts

The action is identical to the one used for UniversalCraft except for the BUILD_ID offset.
EGT is updated to fix a memory leak issue in Loom which would otherwise consume more memory than available on the public GitHub Actions runners.
Also updates the build reference badges in the README to filter by `+` because our new GitHub Actions CI now uses the proper branch name (instead of `pull-#`) for pull request artifacts, so the current `pull` filter is insufficient.

Build: Enable GitHub Actions based CI

---

src/main/kotlin/gg/essential/elementa/constraints/animation/AnimationComponent.kt

The FieldAnimationComponent skips the last frame, as it only sets the value when its not complete, which it is on the last frame.

Fix FieldAnimationComponent skipping last frame

---

src/main/kotlin/gg/essential/elementa/components/ScrollComponent.kt

This makes sure that the `beforeDraw` method is called.

ScrollComponent: Change DefaultScrollBar to be a UIContainer

---

api/Elementa.api
src/main/kotlin/gg/essential/elementa/ElementaVersion.kt
src/main/kotlin/gg/essential/elementa/components/ScrollComponent.kt

This should retain the original behavior where it defaults to preferring vertical when both are enabled. This also allows for not requiring holding shift when horizontal is the only scroll direction.
Closes #123

ScrollComponent: Implement better specification of direction

---

src/main/kotlin/gg/essential/elementa/components/ScrollComponent.kt

This led to scroll components crashing due to coercing to an empty offset range.

ScrollComponent: fix wrong parenthesis

---

src/main/kotlin/gg/essential/elementa/constraints/animation/AnimationStrategy.kt

The strategies didn't completely follow the provided code from https://easings.net/en and would return, for example with OUT_EXPO, 0.999 when percentComplete would be 1.0.

Fix animation strategies IN_EXPO and OUT_EXPO.

---

src/main/kotlin/gg/essential/elementa/components/UIWrappedText.kt

No font was passed to `width`, as such it used the default MC font, which produces incorrect results when trying to use a font that has a different width.

UIWrappedText: Fix incorrect font used for centering

---

src/main/kotlin/gg/essential/elementa/components/input/AbstractTextInput.kt
src/main/kotlin/gg/essential/elementa/impl/Platform.kt
versions/src/main/java/gg/essential/elementa/impl/PlatformImpl.java

It shouldn't ever change and this way the same Elementa build continues to be compatible on 1.20.5+ where the MC method was moved to another class.

AbstractTextInput: Hard-code isAllowedCharacter

---

src/main/kotlin/gg/essential/elementa/WindowScreen.kt

This was clearly wrong; just no one ever noticed because the vanilla content drawn by `super.onDrawScreen` (e.g. vanilla buttons) is usually empty for Elementa screens.
But now that I've seen it, I can't just keep it like that.

WindowScreen: Fix background being draw on top of screen

---

src/main/kotlin/gg/essential/elementa/components/UIText.kt

This fixes an issue on certain versions of Minecraft where the vanilla font provider returns a width of 0 for unsupported characters. This caused the scale to be calculated incorrectly later on, which completely broke rendering.

UIText: Check if the textWidth is 0 instead of if the string is empty

---

src/main/kotlin/gg/essential/elementa/components/Window.kt

This allows effects to be setup correctly if placed on a `Window`.

Window: Call `super.afterInitialization`

---

api/Elementa.api
build.gradle.kts
gradle/wrapper/gradle-wrapper.properties
settings.gradle.kts

Also sets the Kotlin language and API version to keep compatibility with projects using older versions of Kotlin.
Bumped Dokka as I wasn't sure if using a mismatched Kotlin version would cause issues. (do we even need it anymore?)

Build: Bump Kotlin, EGT, and Gradle

---

versions/build.gradle.kts

See [UniversalCraft#73](https://github.com/EssentialGG/UniversalCraft/pull/73)

Fix library being incorrectly declared as a `LIBRARY`

---

api/Elementa.api
src/main/kotlin/gg/essential/elementa/ElementaVersion.kt
src/main/kotlin/gg/essential/elementa/components/ScrollComponent.kt

This will ensure that the vertical scroll bar grip is at least a minimum height, making it easier to grab when there is a lot of content within the ScrollComponent.

ScrollComponent: Add a minimum scrollbar grip size

---

build.gradle.kts
unstable/layoutdsl/build.gradle.kts
unstable/statev2/build.gradle.kts

We used to publish these for the main Elementa artifact but accidentially stopped doing so with 0b76fa7c.
For the unstable artifacts we had never published them.

Build: Publish sources

---

api/Elementa.api
src/main/kotlin/gg/essential/elementa/UIComponent.kt
src/main/kotlin/gg/essential/elementa/components/Window.kt
src/main/kotlin/gg/essential/elementa/components/inspector/Inspector.kt
unstable/layoutdsl/src/main/kotlin/gg/essential/elementa/layoutdsl/containers.kt

The old API is difficult to work with because it will continue to render floating components even if they've been removed from the component tree. Additionally it can CME if components are removed from the floating list during rendering, further complicating the workarounds required.
This new API fixes the issue by tracking when components are removed/added from/to the tree and updating its internal floating list accordingly.
It also allows setting the floating state at any time, even before the component has a parent, another thing the old API did not support.
The order in which floating components appear also differs in the new API. While the old API showed floating components in the order in which they were set to be floating, this often isn't all too useful when the order in which …

UIComponent: Rewrite floating API

---

api/Elementa.api
src/main/kotlin/gg/essential/elementa/UIComponent.kt
src/main/kotlin/gg/essential/elementa/components/UIImage.kt
src/main/kotlin/gg/essential/elementa/components/inspector/Inspector.kt
src/main/kotlin/gg/essential/elementa/components/inspector/InspectorNode.kt
src/main/kotlin/gg/essential/elementa/utils/ResourceCache.kt

This commit tries to track the source code location of components (not where its class is defined but where that particular instance was created) and shows that info in the inspector. Should the automatically determined location be unhelpful (e.g. because it's in a factory function rather than where the factory function is called), then it also allows scrolling while holding the Shift key to go up and down the call stack.
If IntelliJ is running, it will also automatically jump to that source location every time a component is selected in the inspector.

Inspector: Show source file of components and jump there in IntelliJ

---

api/Elementa.api
gradle/libs.versions.toml
src/main/kotlin/gg/essential/elementa/components/GradientComponent.kt
src/main/kotlin/gg/essential/elementa/components/SVGComponent.kt
src/main/kotlin/gg/essential/elementa/components/TreeGraphComponent.kt
src/main/kotlin/gg/essential/elementa/components/UIBlock.kt
src/main/kotlin/gg/essential/elementa/components/UICircle.kt
src/main/kotlin/gg/essential/elementa/components/UIRoundedRectangle.kt
src/main/kotlin/gg/essential/elementa/components/UIShape.kt
src/main/kotlin/gg/essential/elementa/components/UIText.kt
src/main/kotlin/gg/essential/elementa/components/UIWrappedText.kt
src/main/kotlin/gg/essential/elementa/components/image/MSDFComponent.kt
src/main/kotlin/gg/essential/elementa/components/inspector/Inspector.kt
src/main/kotlin/gg/essential/elementa/dsl/utilities.kt
src/main/kotlin/gg/essential/elementa/effects/ScissorEffect.kt
src/main/kotlin/gg/essential/elementa/font/BasicFontRenderer.kt
src/main/kotlin/gg/essential/elementa/font/FontRenderer.kt
src/main/kotlin/gg/essential/elementa/utils/LineUtils.kt
src/main/kotlin/gg/essential/elementa/utils/extensions.kt
src/main/kotlin/gg/essential/elementa/utils/image.kt

Depends on https://github.com/EssentialGG/UniversalCraft/pull/97

Build: Add support for Minecraft 1.21.5

---

src/main/kotlin/gg/essential/elementa/components/Window.kt

These `if`s used to be early returns and were improperly inverted in c199a84db9db85d81bd7da40f25acae05b30cc31.
This is why our integration tests were no longer able to dismiss notifications by dragging them off-screen, because the tests were moving the mouse perfectly horizontally, so no drag event was ever emitted.

Window: Fix incorrect logic in dragging code

---

src/main/kotlin/gg/essential/elementa/components/GradientComponent.kt

This call was accidentally dropped in https://github.com/EssentialGG/Elementa/commit/f9c95e800c8e19187b4ee663117e0c5cf48f9651#diff-bc7125e63fa8e1fe130c0591fecb4078dad770ace6f613ec4ce3cb9729c8ee98L126, breaking translucent GradientComponents on versions prior to 1.21.5 unless blending happens to already be enabled.
UIText always enables blending but does not disable it (MC's font renderer itself only disables it on more modern versions, not sure where the cut-off is but 1.12.2 still leaves it enabled), and one of out two remaining GradientComponent we use in Essential (we've mostly switched to GradientEffect) is on top of text, hence why this wasn't noticed immediately.
Linear: EM-3177

GradientComponent: Fix blending not being enabled
